nameserver: dev
auth: 
  service: qq
  user: 353272497@qq.com
  pass: siecaainetpfcbcb
emails:
  - test@dadigua.men
pickSubscribeEmal:
  - 
    name: api
    emails: 
      - test@dadigua.men
  



  